# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f006abd4cd49a2f8407579702715dc21acebd5923404c8f905e53d460cec0ea6eabbff35a2466f3bbe5b40afcaae42a8383c3631b27ca681c9f59a6d1a58d1cc
  omise_secret_key: skey_test_53toly2lkl58kvdazgu
  omise_public_key: pkey_test_53toly2ll40xt5cvmir
  tookan_api_key: 2b997be77e2cc22becfd4c66426ef504
  tookan_team_id: 255

test:
  secret_key_base: 619aa762fc364454a06dc61b927fb99af656aadbd5a43d56b6438f476b9087d4e497dd65ce39b73eaeda6c750717923f23800067a15aa397e574d31bca2e221c

staging:
  secret_key_base: f006abd4cd49a2f8407579702715dc21acebd5923404c8f905e53d460cec0ea6eabbff35a2466f3bbe5b40afcaae42a8383c3631b27ca681c9f59a6d1a58d1cc
  omise_secret_key: skey_test_53toly2lkl58kvdazgu
  omise_public_key: pkey_test_53toly2ll40xt5cvmir
  tookan_api_key: 2b997be77e2cc22becfd4c66426ef504
  tookan_team_id: 255

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  omise_secret_key: <%= ENV["OMISE_SECRET_KEY"] %>
  omise_public_key: <%= ENV["OMISE_PUBLIC_KEY"] %>
  tookan_api_key: <%= ENV["TOOKAN_API_KEY"] %>
  tookan_team_id: <%= ENV["TOOKAN_TEAM_ID"] %>
